;------------------------------------------------------------------------------
; Filename: mfunc52.mac
; Description: Check XY Zero Position
; Notes:
; Requires: CNC12 V5.40.00+
; Revision Date: 11 NOV 2022
; Please see TB300 or the following link for tips on writing custom macros.
; https://www.centroidcnc.com/centroid_diy/downloads/acorn_documentation/centroid_cnc_macro_programming.pdf
; Copyright SMC 2025
;------------------------------------------------------------------------------
; Parameters:
;
; System Variables:
;
; PLC Variables:
;
; User Variables:
;
;------------------------------------------------------------------------------
IF #50001                        ;Prevent lookahead from parsing past here
IF #4201 || #4202 THEN GOTO 1000 ;Skip macro if graphing or searching

N100

G65 "#400\system\check_laser_xy0.cnc"

N1000                            ;End of Macro